# Generated by Django 4.1.7 on 2023-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='image',
            field=models.ImageField(upload_to='media/images/freelancer_profile/'),
        ),
    ]
