# Generated by Django 4.1.7 on 2023-03-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(default='exit', max_length=70),
            preserve_default=False,
        ),
    ]
