# Generated by Django 4.1.7 on 2023-03-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfreelancer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
