# Generated by Django 4.1.7 on 2023-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerfreelancer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='education',
            field=models.ManyToManyField(null=True, to='authentication.education'),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='experience',
            field=models.ManyToManyField(null=True, to='authentication.experience'),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='overview',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='services',
            field=models.ManyToManyField(null=True, to='authentication.services'),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='skills',
            field=models.ManyToManyField(null=True, to='authentication.skills'),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='street_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registerfreelancer',
            name='user_image',
            field=models.ImageField(null=True, upload_to='static_dirs/images/user_image'),
        ),
    ]
