# Generated by Django 4.1.7 on 2023-03-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_registerfreelancer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerfreelancer',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.jobtitle'),
        ),
    ]
