# Generated by Django 4.1.7 on 2023-03-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_registerfreelancer_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfreelancer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
