# Generated by Django 4.1.7 on 2023-03-27 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessageclient',
            name='is_online',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 21, 6, 49, 550114)),
        ),
    ]
