# Generated by Django 4.1.7 on 2023-03-28 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 1, 51, 2, 854670)),
        ),
    ]
