<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-27 23:17
=======
# Generated by Django 4.1.7 on 2023-03-27 22:23
>>>>>>> 19730ee0514d32ff07cd3bdce6002d71aa66926a

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_chatmessageclient_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 1, 17, 39, 420194)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 0, 23, 34, 889431)),
>>>>>>> 19730ee0514d32ff07cd3bdce6002d71aa66926a
        ),
    ]
