# Generated by Django 4.1.7 on 2023-03-27 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_chatmessageclient_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 1, 17, 39, 420194)),
        ),
    ]
