# Generated by Django 4.1.7 on 2023-03-29 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_chatmessage_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 13, 1, 33, 702008)),
        ),
    ]
