# Generated by Django 4.1.7 on 2023-03-28 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_chatmessage_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='me',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 2, 45, 15, 697604)),
        ),
    ]
