# Generated by Django 4.1.7 on 2023-03-28 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_chatmessage_me_alter_chatmessage_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='me',
            new_name='client',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 4, 24, 40, 927983)),
        ),
    ]
