# Generated by Django 4.1.7 on 2023-03-28 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_rename_me_chatmessage_client_chatmessage_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 18, 54, 7, 708549)),
        ),
    ]
