# Generated by Django 4.1.7 on 2023-03-30 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_alter_chatmessage_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 19, 19, 41, 989363)),
        ),
    ]
