# Generated by Django 4.1.7 on 2023-03-23 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
        migrations.CreateModel(
            name='JobImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/images_job/')),
            ],
        ),
        migrations.CreateModel(
            name='LikeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=1000)),
                ('is_pyment', models.BooleanField(default=False)),
                ('Proposals', models.ManyToManyField(blank=True, to='authentication.registerfreelancer')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser')),
                ('dislikes', models.ManyToManyField(blank=True, to='home_app.dislike')),
                ('images', models.ManyToManyField(blank=True, to='home_app.jobimages')),
                ('likes', models.ManyToManyField(blank=True, to='home_app.likejob')),
                ('skills', models.ManyToManyField(blank=True, to='authentication.skills')),
            ],
        ),
    ]
