# Generated by Django 4.1.7 on 2023-03-28 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesSendApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/applay_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=1000)),
                ('is_pyment', models.BooleanField(default=False)),
                ('is_hire', models.BooleanField(default=False)),
                ('Proposals', models.ManyToManyField(blank=True, to='authentication.registerfreelancer')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser')),
                ('dislikes', models.ManyToManyField(blank=True, to='home_app.dislike')),
            ],
        ),
        migrations.CreateModel(
            name='JobImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/images_job/')),
            ],
        ),
        migrations.CreateModel(
            name='SendApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=20000)),
                ('cost_re', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_hire', models.BooleanField(default=False)),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
                ('images', models.ManyToManyField(blank=True, to='home_app.imagessendapply')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAndRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(max_length=5)),
                ('review', models.CharField(max_length=5000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser')),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
        migrations.CreateModel(
            name='notificationsFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='unread', max_length=264, null=True)),
                ('type_of_notification', models.CharField(blank=True, max_length=264, null=True)),
                ('user_revoker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_revoker', to='authentication.registerfreelancer')),
                ('user_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to='authentication.registeruser')),
            ],
        ),
        migrations.CreateModel(
            name='notificationsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='unread', max_length=264, null=True)),
                ('type_of_notification', models.CharField(blank=True, max_length=264, null=True)),
                ('user_revoker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_revoker', to='authentication.registeruser')),
                ('user_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to='authentication.registerfreelancer')),
            ],
        ),
        migrations.CreateModel(
            name='LikeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ManyToManyField(blank=True, to='home_app.jobimages'),
        ),
        migrations.AddField(
            model_name='job',
            name='likes',
            field=models.ManyToManyField(blank=True, to='home_app.likejob'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='authentication.skills'),
        ),
        migrations.CreateModel(
            name='Hires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_payment', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser')),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.job')),
            ],
        ),
    ]
