# Generated by Django 4.1.7 on 2023-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_pyment',
            field=models.BooleanField(default=False),
        ),
    ]
