# Generated by Django 4.1.7 on 2023-03-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home_app', '0002_job_is_pyment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='dislikes',
            field=models.ManyToManyField(blank=True, to='home_app.dislike'),
        ),
        migrations.AddField(
            model_name='job',
            name='likes',
            field=models.ManyToManyField(blank=True, to='home_app.likejob'),
        ),
    ]
