# Generated by Django 4.1.7 on 2023-03-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home_app', '0002_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='notificationsClient',
        ),
        migrations.AlterField(
            model_name='notificationsclient',
            name='user_revoker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_revoker', to='authentication.registeruser'),
        ),
        migrations.AlterField(
            model_name='notificationsclient',
            name='user_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to='authentication.registerfreelancer'),
        ),
    ]
