# Generated by Django 4.1.7 on 2023-03-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home_app', '0003_rename_notifications_notificationsclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesSendApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/applay_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SendApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=20000)),
                ('cost_re', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
                ('images', models.ManyToManyField(blank=True, to='home_app.imagessendapply')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.job')),
            ],
        ),
    ]
