# Generated by Django 4.1.7 on 2023-03-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home_app', '0004_imagessendapply_sendapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser')),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.job')),
            ],
        ),
    ]
