# Generated by Django 4.1.7 on 2023-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_hires'),
    ]

    operations = [
        migrations.AddField(
            model_name='hires',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hires',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
