# Generated by Django 4.1.7 on 2023-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_hires_is_finish_hires_is_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendapply',
            name='is_hire',
            field=models.BooleanField(default=False),
        ),
    ]
