# Generated by Django 4.1.7 on 2023-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_hires_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_hire',
            field=models.BooleanField(default=False),
        ),
    ]
