# Generated by Django 4.1.7 on 2023-03-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registerfreelancer_is_online_registeruser_is_online'),
        ('home_app', '0011_notificationsfree'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrate',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser'),
            preserve_default=False,
        ),
    ]
