# Generated by Django 4.1.7 on 2023-03-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=5, max_digits=10)),
                ('work_history_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser')),
            ],
        ),
    ]
