# Generated by Django 4.1.7 on 2023-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='CVV',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='Credit_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='Expire_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='Expire_year',
            field=models.CharField(max_length=4),
        ),
    ]
