# Generated by Django 4.1.7 on 2023-03-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portflio',
            name='images',
            field=models.ManyToManyField(to='profile_app.imagesproject'),
        ),
    ]
