# Generated by Django 4.1.7 on 2023-03-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='const',
            new_name='cost',
        ),
    ]
