# Generated by Django 4.1.7 on 2023-03-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
