# Generated by Django 4.1.7 on 2023-03-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='id_user_free',
            new_name='certification_user_freelancer',
        ),
    ]
