# Generated by Django 4.1.7 on 2023-03-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/project_image'),
        ),
        migrations.AlterField(
            model_name='portflio',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='profile_app.imagesproject'),
        ),
    ]
