# Generated by Django 4.1.7 on 2023-03-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnTheCard', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('Zip_code', models.CharField(max_length=30)),
                ('Expire_year', models.IntegerField(verbose_name=4)),
                ('Expire_month', models.IntegerField(max_length=2)),
                ('Credit_number', models.IntegerField(verbose_name=16)),
                ('CVV', models.IntegerField(verbose_name=3)),
            ],
        ),
    ]
