# Generated by Django 4.1.7 on 2023-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_portflio_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproject',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/Portflio_images/'),
        ),
    ]
