# Generated by Django 4.1.7 on 2023-03-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_rename_id_user_free_certification_certification_user_freelancer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='cons',
            new_name='const',
        ),
    ]
