# Generated by Django 4.1.7 on 2023-03-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_workhistoryuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistoryuser',
            old_name='work_history_freelancer',
            new_name='work_history_user',
        ),
    ]
