# Generated by Django 4.1.7 on 2023-03-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('profile_app', '0002_alter_workhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='work_history_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser'),
            preserve_default=False,
        ),
    ]
