# Generated by Django 4.1.7 on 2023-03-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registeruser_city_registeruser_postal_code_and_more'),
        ('profile_app', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.registeruser'),
            preserve_default=False,
        ),
    ]
