# Generated by Django 4.1.7 on 2023-03-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_workhistory_work_history_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
