# Generated by Django 4.1.7 on 2023-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_rename_cons_workhistory_const'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuse_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='imagesproject',
            name='image',
            field=models.ImageField(null=True, upload_to='static_dirs/images/project_image'),
        ),
        migrations.AlterField(
            model_name='portflio',
            name='images',
            field=models.ManyToManyField(null=True, to='profile_app.imagesproject'),
        ),
    ]
