# Generated by Django 4.1.7 on 2023-03-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_registerfreelancer_user_image'),
        ('profile_app', '0004_certification_certification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('name_on_card', models.CharField(max_length=50)),
                ('credit_card_number', models.CharField(max_length=20)),
                ('exp_month', models.DateField()),
                ('exp_year', models.DateField()),
                ('cvv', models.IntegerField(max_length=5)),
                ('payment_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registerfreelancer')),
            ],
        ),
    ]
