# Generated by Django 4.1.7 on 2023-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_portflio_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portflio',
            name='date_time',
            field=models.DateField(null=True),
        ),
    ]
